version: "3.8"

services:
  redis:
    image: redis:6.2.6-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud_network
  db:
    image: postgres:13.6-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    networks:
      - nextcloud_network
      - devops
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - db.env
  app:
    image: nextcloud:23.0.3-apache
    container_name: nextcloud
    ports:
      - "8080:80"
    networks:
      - nextcloud_network
    depends_on:
      - db
      - redis
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html # Main folder, needed for updating
      # - ./app/config:/var/www/html/config # installed / modified apps
      # - ./app/custom_apps:/var/www/html/custom_apps # local configuration
      # - ./app/data:/var/www/html/data # the actual data of your Nextcloud
      # - ./app/themes:/var/www/html/themes # theming/branding
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
    env_file:
      - db.env
volumes:
  nextcloud:
  db:

networks:
  nextcloud_network:
  devops:
    name: devops